<h3>What does this do?</h3>
<p>This module is part of Calguy1000's E-commerce suite.  It provides the ability to optimally combine cart items into one or more packages to aide in reducing shipping costs, and to optimize the shipping estimation process.</p>

<h3>Features:</h3>
<ul>
  <li>Define numerous boxes of different sizes and capacities.</li>
  <li>Allow defining behavior for products that do not have valid dimensions or weights.</li>
  <li>Allow creating custom oversized packages for products that do not fit into any of the defined boxes.</li>
  <li>Generates a packing list object that is visible from within the Orders module.</li>
</ul>

<h3>Requirements:</h3>
<p>This module requires, or assumes that all (or most) of your products will have defined package dimensions, and a defined weight.  If you have not already done this, then you should create a new &quuot;dimensions&quot; field in the Products module,  and modify each of your products so that the package dimensions are defined and accurate.</p>

<h3>How Do I Use It:</h3>
<ul>
  <li>After installing this module, you should visit the module's admin panel and define one or more box sizes.
     <p>Usually these are the box sizes that your store carries in stock.  You should enter the outer and inner dimensions, and the maximum weight capacity of each box.</p>
  </li>
  <li>Next visit the settigns tab of the module's admin panel and define the policy for oversize, overweight products and the policy for products that have no weight or dimensions.</li>
  <li>Lastly, visit the admin panel of the CGEcommerceBase module, and set this module as the &quot;packaging&module.</li>
</ul>

<h3>Support</h3>
<p>The module author is in no way obligated to provide support for this code in any fashion.  However, there are a number of resources available to help you with it:</p>
<ul>
<li>A bug tracking and feature request system has been created for this module <a href="http://dev.cmsmadesimple.org/projects/products">here</a>.  Please be verbose and descriptive when submitting bug reports and feature requests, and for bug reports ensure that you have provided sufficient information to reliably reproduce the issue.</li>
<li>Additional discussion of this module may also be found in the <a href="http://forum.cmsmadesimple.org">CMS Made Simple Forums</a>.  When describing an issue please make an effort to provide all relavant information, a thorough description of your issue, and steps to reproduce it or your discussion may be ignored.</li>
<li>The author, calguy1000, can often be found in the <a href="irc://irc.freenode.net/#cms">CMS IRC Channel</a>.</li>
<li>Lastly, you may have some success emailing the author directly.  However, please use this as a last resort, and ensure that you have followed all applicable instructions on the forge, in the forums, etc.</li>
</ul>

<h3>Copyright and License</h3>
<p>Copyright &copy; 2017, Robert Campbell <a href="mailto:calguy1000@cmsmadesimple.org">&lt;calguy1000@cmsmadesimple.org&gt;</a>. All Rights Are Reserved.</p>
<p>This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.</p>
<p>However, as a special exception to the GPL, this software is distributed
as an addon module to CMS Made Simple.  You may not use this software
in any Non GPL version of CMS Made simple, or in any version of CMS
Made simple that does not indicate clearly and obviously in its admin
section that the site was built with CMS Made simple.</p>
<p>This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
Or read it <a href="http://www.gnu.org/licenses/licenses.html#GPL">online</a></p>
